### PR TITLE
Use findup to traverse tree for .git, package.json

### LINKED ISSUE #35: Using git `--work-tree` option blows up with ghooks
I know this is a weird issue, but I've just encountered that using `--work-tree` (as in `git --work-tree some/folder commit`) causes ghooks to blow up with the following:

```js
$ git --work-tree ./foo commit -m 'an example of --work-tree crashing'
module.js:339
    throw err;
    ^

Error: Cannot find module '<snip>/ghooks-test/foo/package'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at commandFor (<snip>/ghooks-test/node_modules/ghooks/lib/runner.js:17:13)
    at run (<snip>/ghooks-test/node_modules/ghooks/lib/runner.js:8:17)
    at <snip>/ghooks-test/.git/hooks/pre-commit:7:20
    at Object.<anonymous> (<snip>/ghooks-test/.git/hooks/pre-commit:8:3)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
```

I think it's a case of simply try/catching and just cracefully failing if the package.json cannot be found. I'm happy to work on a PR if you're happy to accept one? 

FYI if you're thinking "what in the world are you using --work-tree for?!" - well, I'm trying to have a gh-pages branch which tracks my `site` directory (rather than repo root) - using https://github.com/lukekarrys/git-directory-deploy

### PR DESCRIPTION
**Pull request by keithamus**
Fixes #35, #28, #3. Closes #36

This uses the [findup] package to traverse up the directory tree of
the current working directory, to find `package.json`, or `.git`.
It does so to allow for edge-case situations, such as described in
and #35 (executing hooks from a different working dir, for example
with `git --work-tree`).

As part of this commit, the JSHint maxcomplexity/maxstatements
numbers have been bumped by 1.

[findup]: https://www.npmjs.com/package/findup

---

Note: I think #36 (/cc @gtramontina) should be closed as the functionality in this PR overlaps that of #36.

### CODE REVIEW

**Comment by kentcdodds** [comment]
I'll give this a closer look later, but I just saw this last night. Maybe you'll think it's useful? https://github.com/sindresorhus/read-pkg-up https://github.com/sindresorhus/find-up

**Comment by kentcdodds** [comment]
Oh, also https://github.com/sindresorhus/pkg-conf

**Comment by keithamus** [comment]
@kentcdodds they all do pretty much the same thing. Whichever one you want to use I'm happy with, I just picked `findup` because it was the first on google and the code seemed fine and it has tests.

**Comment by kentcdodds** [comment]
I trust your judgment to know which makes our codebase simpler and better tested :+1: Let me know what you think. If you wish to keep it the way it is, I'm cool with that :D

**Comment by keithamus** [comment]
I think we can stick with `findup`. It certainly has _more_ tests than `find-up` (better covered or better tests is arguable). I think `read-pkg-up` and `pkg-conf`, while useful, would introduce extra dependencies for little reason. findup works well for both `.git.` and `package.json`.

**Comment by kentcdodds** [comment]
This is fantastic. Merging and releasing a new version. Thanks!

**Comment by keithamus** [comment]
:+1:

**Comment by gtramontina** [comment]
I'm late in the game here... but this is great!! Thanks a lot! :beers:
I only have a couple of comments that can be addresses some other time (adding them inline).

File: lib/install.js [hunk 1]
```diff
@@ -28,16 +26,22 @@ var hooks = [
...
+  } catch(e) {
+    return null;
   }
-  else { warnAboutGit(); }
 }
 
-function isGitProject () {
-  return fs.existsSync(resolve(projectRoot, '.git'));
+function installHooks (directory) {
+  var gitRoot = findGitRoot(directory);
```
Comment (gtramontina) [inline lib/install.js]: I believe that this is the reason why you had to bump the `maxcomplexity` up to 3.
We never pass in a `directory` to `installHooks`, so `findGitRoot` also take no parameters and use `cwd` directly. This would bring that function's cyclomatic complexity back to 2, I believe.

Comment (kentcdodds) [inline lib/install.js]: :+1: I'd be cool with keeping maxcomplexity down

File: test/runner.test.js [hunk 2]
```diff
@@ -18,6 +24,12 @@ describe('runner', function () {
     }
   }}));
 
+  it('looks for `package.json` using findup, starting with process.cwd()', function () {
```
Comment (gtramontina) [inline test/runner.test.js]: I've just realized... This spec dictates the implementation (`…using findup…`). Whether we use a direct `require` or `findup` to find `package.json` is an implementation detail IMO and doesn't add much, given we already have tests that cover executing the hooks specified in the `package.json`.

I'll put up a PR addressing this and a few other minor cleanups.
